### ISSUE TITLE
Smithy does not compile with Rust 1.56.0-beta. (Conflict between num-integer crate and std)

### ISSUE THREAD

**Issue by tatsuya6502** [awslabs/smithy-rs#700]
Hi. I found that Smithy does not compile with the current Rust beta (1.56.0-beta.2). It fails with the following error:

```console
   Compiling smithy-types v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.17-alpha#74cd8a14)
error[E0658]: use of unstable library feature 'int_roundings'
Error:    --> ... /smithy-types/src/instant/mod.rs:150:61
    |
150 |         let subsec_millis = i64::from(self.subsecond_nanos).div_floor(&(NANOS_PER_MILLI as i64));
    |                                                             ^^^^^^^^^
    |
    = note: see issue #88581 <https://github.com/rust-lang/rust/issues/88581> for more information
```

**Smithy versions**

- I found this issue with v0.19. That is the version used by the current alpha version of AWS SDK for Rust.
- But I believe the latest Smithy version (the head of main branch) has the same issue.

**How to reproduce**

To reproduce, run `cargo +beta check` to compile Smithy.

**Root cause analysis**

The `div_floor` method used [here](https://github.com/awslabs/smithy-rs/blob/7fa4af4a9367aeca6d55e26fc4d4ba93093b90c4/rust-runtime/smithy-types/src/instant/mod.rs#L150) is provided by num-integer crate. However an unstable method with the same name has been added to std (https://github.com/rust-lang/rust/issues/88581), so they are conflicting. Note that the Rust library team considers that this is an acceptable breakage: https://github.com/rust-lang/rust/issues/88581#issuecomment-912206298. 

**Solving the issue**

I have not tried by myself but I think changing this expression:

```rust
i64::from(self.subsecond_nanos).div_floor(&(NANOS_PER_MILLI as i64))
```

to the following will solve the issue:

```rust
Integer::div_floor(&i64::from(self.subsecond_nanos), &(NANOS_PER_MILLI as i64))
```

Here is a similar fix in num-bigint crate:
- https://github.com/rust-num/num-bigint/pull/220/files

**Comment by rcoh** [comment]
thanks for the report! #694 is queued to merge and will resolve this issue.
